### ISSUE TITLE
metamodel

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#226]
Implement the metamodel. Here's what needs to be done:
- [x] Define Ceylon interfaces
- [x] Provide Java implementations
- [x] Test (currently in compiler `metamodel/runtime`)
- [x] Support annotations
- [x] Support invoking method/constructors
- [x] Support invoking toplevel methods
- [x] Support reading/writing attributes
- [x] Support default arguments for methods/initialisers
- [x] Support variadic arguments for methods/initialisers
- [x] Support member classes/interfaces (and `formal`)
- [x] Support methods with multiple parameter lists (currently lost by the model loader)
- [x] Support local declarations -> moved to 1.0 #260
- [x] Rename to `ceylon.language.model`
- [x] Support object declarations
- [x] Support alias declarations
- [x] Unreify/erase private attributes/methods (even for Java types) -> Moved to #297
- [x] Add `Class.parameters` and `Function.parameters` -> Moved to 1.0 #296
- [x] Support union/intersection type members -> Moved to 1.0 #295
- [x] Java interop (to be expanded)
  - [x] Java primitive types
  - [x] Java properties
  - [x] Java fields
  - [x] Java static fields/methods -> Moved to 1.0 #294
  - [x] Java overloaded methods/constructors -> Moved to 1.0 #293
  - [x] Java inner class constructors (doesn't use factory methods unlike Ceylon)
- [x] Reify method/initialiser parameters
- [x] Reify class/interface/method type parameters
- [x] Reify module imports
- [x] Support dynamic loading of modules -> moved to 1.0 #280
- [x] Support looking up modules by name/version
- [x] Support looking up classes by name -> moved to 1.0 #282
- [x] Add distinction between declared/inherited members
- [x] Properly deal with locking
- [x] Implement verification of type constraints when applying types
- [x] Implement verification of reified type arguments
- [x] Implement verification of container types for memberApply
- [x] Implement hash/equals/string on the metamodel
- [x] Fix all remaining FIXME/TODO
- [x] Add attribute for getting fully qualified name (probably into `Declaration`)
- [x] Add attribute for getting container (probably into `TopLevelOrMemberDeclaration`)
- [x] Do not wrap exceptions in invocations
- [x] Add `abstract`, `shared`, `actual`, `formal` and `default` attributes to declarations
- [x] Deal with `UnknownType` -> moved to 1.0 #289
- [x] Add a way to get from a `Member` to its `Declaration`?
- [x] Implement the `$call$variadic` methods
- [x] Add `is` to `Type`?
- [x] Add a container type parameter to member apply
- [x] Change names to US-English
- [x] Check what happens WRT abstract classes and invoking their constructors
- [x] Figure out how to properly implement AliasDeclaration.apply/memberApply -> #298
